<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" x="${camera_length}" y="${camera_width}" z="${camera_height}"
                           o_xyz="0 0 0" o_rpy="0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(0.4 + camera_length)/2.0} 0 0" rpy="0 0 0" />
    </joint>

    <link name="camera_link_optical" />

    <joint name="camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="camera_link"/>
        <child link="camera_link_optical" />
    </joint>

    <!-- <gazebo reference="camera_link">
        <sensor name="depth_camera" type="depth_camera">
            <update_rate>10</update_rate>
            <topic>depth_camera</topic>
            <camera>
                <horizontal_fov>1.05</horizontal_fov>
                <image>
                    <width>256</width>
                    <height>256</height>
                    <format>B8G8R8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>10.0</far>
                </clip>
            </camera>
            <gz_frame_id>camera_link</gz_frame_id>
        </sensor>
    </gazebo>

    <gazebo reference="camera_link">
        <sensor name='camera' type='depth'>"
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
            <camera_info_topic>camera/camera_info</camera_info_topic>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>8.0</far>
                </clip>
            </camera>
            <topic>camera/image_raw</topic>
            <gz_frame_id>camera_link_optical</gz_frame_id>
        </sensor>
    </gazebo> -->

    <gazebo reference="camera_link">
        <!-- Depth Camera -->
        <sensor name="depth_camera" type="depth_camera">
            <update_rate>10</update_rate>
            <topic>depth_camera</topic>
            <camera>
            <horizontal_fov>1.05</horizontal_fov>
            <image>
                <width>256</width>
                <height>256</height>
                <format>B8G8R8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>10.0</far>
            </clip>
            </camera>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <gz_frame_id>camera_link</gz_frame_id>
        </sensor>

        <!-- RGB Camera -->
        <sensor name="rgb_camera" type="camera">
            <update_rate>10</update_rate>
            <topic>rgb_camera/image_raw</topic>
            <camera>
            <horizontal_fov>1.05</horizontal_fov>
            <image>
                <width>256</width>
                <height>256</height>
                <format>B8G8R8</format>
            </image>
            <clip>
                <near>0.1</near>
                <far>10.0</far>
            </clip>
            </camera>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <gz_frame_id>camera_link</gz_frame_id>
        </sensor>
    </gazebo>

</robot>
